CREATE USER 'STAFF'@'LOCALHOST' IDENTIFIED BY '1Q2W3E4R!';
GRANT SELECT,INSERT
	ON hanip_delivery.*
    TO 'STAFF'@'LOCALHOST';

GRANT SELECT,INSERT
	ON `day07.4.29`.*
    TO 'STAFF'@'LOCALHOST';

GRANT SELECT,INSERT,UPDATE 
	ON `day07.4.29`.* 
	TO 'STAFF'@'LOCALHOST';


GRANT ALL privileges ON `day07.4.29`.* TO 'STAFF'@'LOCALHOST';
REVOKE UPDATE ON `day07.4.29`.* FROM 'STAFF'@'LOCALHOST'; -- 권환 회수

SELECT * FROM MYSQL.USER;
SHOW GRANTS FOR 'STAFF'@'LOCALHOST';

DROP USER IF exists 'STAFF'@'LOCALHOST'; -- 계정 삭제
SELECT * FROM MYSQL.USER;

GRANT ALL privileges ON *.* TO 'STAFF'@'LOCALHOST'